### ISSUE TITLE
Prateek

### ISSUE THREAD

**Issue by ScizorScara** [kunalwavhule/Test#2]
`using System;
using System.Collections.Generic;
using System.Text;

namespace ConsoleApp1
{
    class Class1
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World 2.0!");
        }
    }
}
   
`

**Comment by ScizorScara** [comment]
![image](https://user-images.githubusercontent.com/61153298/185926440-691f3707-8fe5-4b65-921f-09b79a1e33af.png)

**Comment by kunalwavhule** [comment]
The best way to learn Java programming is by practicing examples. The page contains examples on basic concepts of Java. You are advised to take the references from these examples and try them on your own.

All the programs on this page are tested and should work on all platforms.

**Comment by ScizorScara** [comment]
Bass Na Main me error he Prop me jaake change karde
